const API_BASE_PATH =
  process.env.NODE_ENV === "production"
    ? process.env.REACT_APP_PROD_API_BASE_PATH
    : process.env.REACT_APP_DEV_API_BASE_PATH;

export const config = {
  BASE_PATH: API_BASE_PATH,
  USER_REGISTER: process.env.REACT_APP_DEV_API_AUTH_USER_REGISTER,
  USER_LOGIN: process.env.REACT_APP_DEV_API_AUTH_USER_LOGIN,
  COOKS: process.env.REACT_APP_DEV_API_COOK_GET_ALL_COOKS,
  COOK_BY_BUSINESSNAME:
    process.env.REACT_APP_DEV_API_COOK_GET_COOK_BY_BUSINESSNAME,
  PENDING_COOKS: process.env.REACT_APP_DEV_API_COOK_GET_ALL_PENDING_COOKS,
  COOK_CREATE_PROFILE: process.env.REACT_APP_DEV_API_COOK_CREATE_PROFILE,
  MENU: process.env.REACT_APP_DEV_API_MENU_BASE_PATH,
  COOK: process.env.REACT_APP_DEV_API_MENU_BY_COOK,
  MEAL: process.env.REACT_APP_DEV_API_MENU_BY_MEAL,
  MENU_CREATE_SCHEDULE: process.env.REACT_APP_DEV_API_MENU_CREATE_SCHEDULE,
  MENU_UPDATE_SCHEDULE: process.env.REACT_APP_DEV_API_MENU_UPDATE_SCHEDULE,
  MENU_DELETE_SCHEDULE: process.env.REACT_APP_DEV_API_MENU_DELETE_SCHEDULE,
  MENU_CREATE_DISH: process.env.REACT_APP_DEV_API_MENU_CREATE_DISH,
  MENU_UPDATE_DISH: process.env.REACT_APP_DEV_API_MENU_UPDATE_DISH,
  MENU_DELETE_DISH: process.env.REACT_APP_DEV_API_MENU_DELETE_DISH,
  MENU_ADD_DISH_TO_MEAL: process.env.REACT_APP_DEV_API_MENU_ADD_DISH_TO_MEAL,
  MENU_ADD_MEAL_TO_SCHEDULE:
    process.env.REACT_APP_DEV_API_MENU_ADD_MEAL_TO_SCHEDULE,
  MENU_UPDATE_MEAL_TO_SCHEDULE:
    process.env.REACT_APP_DEV_API_MENU_UPDATE_MEAL_TO_SCHEDULE,
  MENU_DELETE_MEAL: process.env.REACT_APP_DEV_API_MENU_DELETE_MEAL,
  MENU_GET_DISHES_BY_COOK:
    process.env.REACT_APP_DEV_API_MENU_GET_DISHES_BY_COOK,
  MENU_GET_DISHES_BY_MEAL:
    process.env.REACT_APP_DEV_API_MENU_GET_DISHES_BY_MEAL,
  ORDER_PAYMENT: process.env.REACT_APP_DEV_API_ORDER_PAYMENT,
  ORDER: process.env.REACT_APP_DEV_API_ORDER,
  CREATE_ORDER: process.env.REACT_APP_DEV_API_CREATE_ORDER,
  UPDATE_ORDER_STATUS: process.env.REACT_APP_DEV_API_ORDER_UPDATE_STATUS,
  ORDER_BY_CUSTOMER: process.env.REACT_APP_DEV_API_ORDER_BY_CUSTOMER_ID,
  CUSTOMERS: process.env.REACT_APP_DEV_API_CUSTOMERS,
  CUSTOMERS_CREATE_PROFILE:
    process.env.REACT_APP_DEV_API_CUSTOMERS_CREATE_PROFILE,
  STRIPE_PUBLISHABLE_API_KEY: process.env.STRIPE_PUBLISHABLE_API_KEY,
};
